### ISSUE TITLE
O update passa o userId no path para identificar o user a que fazemos update.

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/UsersDemo#1]
https://github.com/vDalken/UsersDemo/blob/c646a0c173043be2e72706513e872582a541d6eb/src/main/java/com/mindera/fabio/usersdemo/restcontrollers/UserController.java#L32

No controller valida logo q o userId do path e o userId do body fazem match e se n fizer podes lançar uma custom exception (eg. UserDoesNotMatchException extends RuntimeException).

**Comment by fabiofilipesilva** [comment]
assim? public User updateUser(@PathVariable Long id, @RequestBody User user){
        if(!Objects.equals(id, user.getId())){
            throw new UserDoesNotMatchException();
        }
        return service.updateUser(user);
    } Estive agora a pesquisar e entendi o porquê de verificar o id se é igual ao body. Percebi que é good practice incluir o identificador único do object no path para que haja previsibilidade, certo?

**Comment by giselacostamindera** [comment]
Sim :)
