### ISSUE TITLE
Podias validar o user q recebes do repositorio: if user==null throw UserNotFoundException

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/UsersDemo#2]
https://github.com/vDalken/UsersDemo/blob/c646a0c173043be2e72706513e872582a541d6eb/src/main/java/com/mindera/fabio/usersdemo/services/UserService.java#L21

Vamos aprender a mapear as custom exceptions na aula.

**Comment by fabiofilipesilva** [comment]
Criei uma custom exception e fiz a verificação. Também andei a ler sobre exception chaining e gostava de saber se isso é muito usado? Parece ser muito bom para guardar detalhes de possiveis erros mas continuar uma mensagem fácil para o cliente entender.   Eu alterei o metodo para @GetMapping("/{userID}")
    public User getUserById(@PathVariable Long userID){
        User user = service.getUserById(userID);
        if(user.equals(null)){
            throw new UserNotFoundException();
        }
        return user;
    }
