### ISSUE TITLE
No update tb podias lançar UserNotFoundException se o user n existe

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/UsersDemo#3]
https://github.com/vDalken/UsersDemo/blob/c646a0c173043be2e72706513e872582a541d6eb/src/main/java/com/mindera/fabio/usersdemo/services/UserService.java#L29

**Comment by fabiofilipesilva** [comment]
Eu reparei que o meu updateUser estava a returnar o objecto mesmo que fosse updated ou não então resolvi fazê-lo returnar null se não encontrar. Usei um boolean e returnei verdade se entrar dentro da função map:  public User updateUser(final User user) {
        boolean userUpdated = users
                .stream()
                .filter(listUser -> Objects.equals(listUser.getId(), user.getId()))
                .findFirst()
                .map(listUser -> {
                    listUser.setName(user.getName());
                    listUser.setPassword(user.getPassword());
                    return true;
                })
                .orElse(false);

        return userUpdated ? user : null;
    }
E depois fiz a checagem no request handler da minha aplicação (no método de updateUser):  User newUser = service.updateUser(user);
        if(newUser.equals(null)){
            throw new UserNotFoundException();
        }

**Comment by giselacostamindera** [comment]
Acho q agora já n precisas disto, pk validas se o user existe no serviço e se não existe fazes throw the UserNotFoundException. Acho q agora o user nunca é null, portanto podes remover a lógica do controller. Mas como tinhas dantes fazia sentido.
