### ISSUE TITLE
No need for this here if User does not exist you are throwing the exception on the UserService

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/UsersDemo#6]
https://github.com/vDalken/UsersDemo/blob/f9591b2a6c9b8496c67501d8c937e844dcfd968f/src/main/java/com/mindera/fabio/usersdemo/restcontrollers/UserController.java#L45

**Comment by fabiofilipesilva** [comment]
Done. I cleaned up the method and pushed the commit. Thank you for noticing my error
